services:
  postgres:
    container_name: "Master_thesis"
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=master_thesis_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: