class Movie
  attr_accessor :movie_id,
                :title,
                :original_language,
                :overview,
                :popularity,
                :release_date,
                :budget,
                :revenue,
                :runtime,
                :status,
                :tagline,
                :vote_average,
                :vote_count,
                :poster_path,
                :backdrop_path,
                :production_companies,
                :credits,
                :keywords,
                :genres,
                :recommendations
end
